/*
 * MainScreen.java
 *
 * Created on May 9, 2011, 10:19:18 PM
 * This java code is the representation of main screen 
 * consider this main screen GUI in package [com.bth.nrk.main]
 */

package com.bth.nrk.main;

/* importing the following library packages required for further operations 
 * (1)[java.io.IOException] is for input and output operations
 * (2)[javax.swing.JOptionPane] is for pop-up messages when triggered
 * (3)[com.bth.nrk.ui.admin.AdminLoginScreen]is include the GUI of admin login
 * (4)[com.bth.nrk.ui.user.UserDetailsScreen] is to include the GUI of Subject login
 * (5)[com.bth.mos.MosConstants] is to provide all the GUI screens should have constant length and height
 */

import java.io.IOException;

import javax.swing.JOptionPane;

import com.bth.mos.MosConstants;
import com.bth.nrk.ui.admin.AdminLoginScreen;
import com.bth.nrk.ui.user.UserDetailsScreen;

/**
 * 
 * @author Kalyan
 * 
 *         Declaring MAinScreen class which is the extention class(sub-class)
 * 
 */
public class MainScreen extends javax.swing.JFrame {

	/**
	 * Declaring the Admin login Screen as well as User details screen.
	 */
	private static final long serialVersionUID = 1L;
	private final AdminLoginScreen mAdminLoginScreen = new AdminLoginScreen();
	private final UserDetailsScreen mUserDetailsScreen = new UserDetailsScreen();

	/** Creates new form MainScreen */
	public MainScreen() {
		/**
		 * Declaring the components required for MAinscreen GUI All the required
		 * components are declared in inintComponents method.
		 */

		initComponents();
		setSize(MosConstants.xSize, MosConstants.ySize);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed"
	// <editor-fold defaultstate="collapsed"
	// <editor-fold defaultstate="collapsed"
	// <editor-fold defaultstate="collapsed"
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		buttonGroup1 = new javax.swing.ButtonGroup();
		jPanel1 = new javax.swing.JPanel();
		jPanel2 = new javax.swing.JPanel();
		exitButton = new javax.swing.JButton();
		userRadioBtn = new javax.swing.JRadioButton();
		adminRadioBtn = new javax.swing.JRadioButton();
		okButton = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		readmeButton = new javax.swing.JButton();
		jLabel7 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("MOS tool");
		setForeground(new java.awt.Color(51, 51, 51));
		setResizable(false);
		setUndecorated(true);

		jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MOS tool", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
		jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
		jPanel1.setDoubleBuffered(false);
		jPanel1.setMinimumSize(new java.awt.Dimension(800, 600));

		exitButton.setText("Exit");
		exitButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
		exitButton.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				exitButtonActionPerformed(evt);
			}
		});

		buttonGroup1.add(userRadioBtn);
		userRadioBtn.setText("Subject");
		userRadioBtn.setBorder(javax.swing.BorderFactory.createTitledBorder("MOS Tool"));
		userRadioBtn.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				userRadioBtnActionPerformed(evt);
			}
		});

		buttonGroup1.add(adminRadioBtn);
		adminRadioBtn.setSelected(true);
		adminRadioBtn.setText("Admin");
		adminRadioBtn.setBorder(javax.swing.BorderFactory.createTitledBorder("MOS Tool"));
		adminRadioBtn.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				adminRadioBtnActionPerformed(evt);
			}
		});

		okButton.setText("OK");
		okButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
		okButton.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				okButtonActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						jPanel2Layout.createSequentialGroup().addContainerGap(72, Short.MAX_VALUE)
								.addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
								.addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE).addGap(34, 34, 34))
				.addGroup(
						jPanel2Layout.createSequentialGroup().addGap(103, 103, 103)
								.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(userRadioBtn).addComponent(adminRadioBtn))
								.addGap(103, 103, 103)));

		jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] { exitButton, okButton });

		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel2Layout
						.createSequentialGroup()
						.addContainerGap()
						.addComponent(adminRadioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(userRadioBtn)
						.addGap(63, 63, 63)
						.addGroup(
								jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap(66, Short.MAX_VALUE)));

		jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] { exitButton, okButton });

		jLabel1.setBackground(new java.awt.Color(204, 204, 204));
		jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14));
		jLabel1.setText("                                      ***Welcome to the Subjective video quality assessment tool***");

		jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11));
		jLabel5.setText("* Please read the instructions by pressing Instructions button");

		readmeButton.setText("Instructions");
		readmeButton.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				readmeButtonActionPerformed(evt);
			}
		});

		jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11));
		jLabel7.setText("* Please read instructions before performing video quality assessment survey");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel1Layout
						.createSequentialGroup()
						.addGroup(
								jPanel1Layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addComponent(jLabel7))
										.addGroup(jPanel1Layout.createSequentialGroup().addGap(21, 21, 21).addComponent(readmeButton))
										.addGroup(
												jPanel1Layout
														.createSequentialGroup()
														.addGap(247, 247, 247)
														.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(
												jPanel1Layout.createSequentialGroup().addContainerGap()
														.addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE))
										.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addComponent(jLabel5))).addContainerGap()));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel1Layout.createSequentialGroup().addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE).addGap(16, 16, 16).addComponent(readmeButton)
						.addGap(27, 27, 27)
						.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(69, Short.MAX_VALUE)));

		jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bth/resources/BTH.jpg"))); // NOI18N
		jLabel6.setText("jLabel6");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup()
						.addGroup(
								layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(
												layout.createSequentialGroup().addGap(559, 559, 559)
														.addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(
												layout.createSequentialGroup()
														.addGap(195, 195, 195)
														.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))).addContainerGap(712, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addGap(23, 23, 23).addComponent(jLabel6).addGap(29, 29, 29)
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap(753, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void readmeButtonActionPerformed(java.awt.event.ActionEvent evt) {
		/*
		 * Event to happen when readme button is pressed
		 */
		Runtime r = Runtime.getRuntime();
		/*
		 * Calling the getRuntime method
		 */
		try {
			r.exec("notepad.exe ReadMe.txt");
			/*
			 * Executing the notepad.exe to generate ReadMe text for the show
			 * the text on the document This read me text have the information
			 * regarding the instructions to use this tool
			 */
		} catch (IOException ex) {
			// Ignore
		}
	}// GEN-LAST:event_readmeButtonActionPerformed

	private void userRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_userRadioBtnActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_userRadioBtnActionPerformed

	private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_exitButtonActionPerformed
		System.exit(1);
		/*
		 * When exit button is selected we make System exit method as true, to
		 * exit the survey
		 */
	}// GEN-LAST:event_exitButtonActionPerformed

	private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {/*
																		 * If ok
																		 * button
																		 * is
																		 * selcted
																		 * we
																		 * implemented
																		 * a
																		 * logic
																		 * to
																		 * check
																		 * whether
																		 * it
																		 * ahs
																		 * selected
																		 * admin
																		 * radio
																		 * button
																		 * or
																		 * user
																		 * radio
																		 * button
																		 */
		try {

			validateMinimalInputs();
			if (adminRadioBtn.isSelected()) {
				/*
				 * If admin radio button is selected admin login screen should
				 * be visible
				 */
				mAdminLoginScreen.setVisible(true);

			} else if (userRadioBtn.isSelected()) {
				/*
				 * Else if user radio button is selected user details screen
				 * should be set visible
				 */
				mUserDetailsScreen.setVisible(true);
			}

			this.setVisible(false);
		} catch (Exception ex) {
			/*
			 * we through an simple exception for try excution *
			 */
			JOptionPane.showMessageDialog(null, ex.getLocalizedMessage());
		}

	}// GEN-LAST:event_okButtonActionPerformed

	private void adminRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_adminRadioBtnActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_adminRadioBtnActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JRadioButton adminRadioBtn;
	private javax.swing.ButtonGroup buttonGroup1;
	private javax.swing.JButton exitButton;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JButton okButton;
	private javax.swing.JButton readmeButton;
	private javax.swing.JRadioButton userRadioBtn;

	// End of variables declaration//GEN-END:variables

	private void validateMinimalInputs() throws Exception {
		/*
		 * IF neither of radio buttons(Admin || User) is selected we declare the
		 * reply as please select one of the options above.
		 */
		if (!adminRadioBtn.isSelected() && !userRadioBtn.isSelected()) {
			throw new Exception("Please select one of the options above.");
		}
	}

}
