/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CustomScalePanel.java
 *
 * Created on Jun 5, 2011, 3:46:08 PM
 */
package com.bth.nrk.ui.user;

/**
 * 
 * @author Kalyan
 */
public class CustomScalePanel extends AbstractScalePanel {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/** Creates new form CustomScalePanel */
	public CustomScalePanel() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		buttonGroup1 = new javax.swing.ButtonGroup();
		maxTextField = new javax.swing.JTextField();
		midRadioButton = new javax.swing.JRadioButton();
		maxRadioButton = new javax.swing.JRadioButton();
		midTextField = new javax.swing.JTextField();
		minTextField = new javax.swing.JTextField();
		minRadioButton = new javax.swing.JRadioButton();

		maxTextField.setEditable(false);
		maxTextField.setText("Best");

		buttonGroup1.add(midRadioButton);
		midRadioButton.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				midRadioButtonActionPerformed(evt);
			}
		});

		buttonGroup1.add(maxRadioButton);

		midTextField.setEditable(false);
		midTextField.setText("Good");
		midTextField.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				midTextFieldActionPerformed(evt);
			}
		});

		minTextField.setEditable(false);
		minTextField.setText("Bad");

		buttonGroup1.add(minRadioButton);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(midRadioButton).addComponent(maxRadioButton).addComponent(minRadioButton))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(
								layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false).addComponent(minTextField).addComponent(midTextField)
										.addComponent(maxTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup()
						.addGroup(
								layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(maxRadioButton)
										.addGroup(
												layout.createSequentialGroup()
														.addComponent(maxTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
														.addGroup(
																layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																		.addComponent(midTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGroup(layout.createSequentialGroup().addGap(1, 1, 1).addComponent(midRadioButton)))))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(
								layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(minTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(minRadioButton)).addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
	}// </editor-fold>//GEN-END:initComponents

	private void midRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_midRadioButtonActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_midRadioButtonActionPerformed

	private void midTextFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_midTextFieldActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_midTextFieldActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.ButtonGroup buttonGroup1;
	private javax.swing.JRadioButton maxRadioButton;
	private javax.swing.JTextField maxTextField;
	private javax.swing.JRadioButton midRadioButton;
	private javax.swing.JTextField midTextField;
	private javax.swing.JRadioButton minRadioButton;
	private javax.swing.JTextField minTextField;

	// End of variables declaration//GEN-END:variables
	@Override
	public int getGrade() {
		if (maxRadioButton.isSelected()) {
			return 3;
		} else if (midRadioButton.isSelected()) {
			return 2;
		} else if (minRadioButton.isSelected()) {
			return 1;
		}
		return -1;
	}

	@Override
	public void reset() {
		buttonGroup1.clearSelection();
	}

	@Override
	public void enableOrDisableInputFields(boolean isEnable) {
		reset();
		maxRadioButton.setEnabled(isEnable);
		midRadioButton.setEnabled(isEnable);
		minRadioButton.setEnabled(isEnable);
	}
}
