/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CustomScalePanel.java
 *
 * Created on Jun 5, 2011, 3:46:08 PM
 */
package com.bth.nrk.ui.user;

/**
 * 
 * @author Kalyan
 */
public class FivePointScalePanel extends AbstractScalePanel {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/** Creates new form CustomScalePanel */
	public FivePointScalePanel() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed"
	// <editor-fold defaultstate="collapsed"
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		buttonGroup1 = new javax.swing.ButtonGroup();
		oneRadioButton = new javax.swing.JRadioButton();
		threeRadioButton = new javax.swing.JRadioButton();
		twoRadioButton = new javax.swing.JRadioButton();
		fourRadioButton = new javax.swing.JRadioButton();
		fiveRadioButton = new javax.swing.JRadioButton();

		buttonGroup1.add(oneRadioButton);
		oneRadioButton.setText("1 Bad");

		buttonGroup1.add(threeRadioButton);
		threeRadioButton.setText("3 Fair");

		buttonGroup1.add(twoRadioButton);
		twoRadioButton.setText("2 Poor");

		buttonGroup1.add(fourRadioButton);
		fourRadioButton.setText("4 Good");

		buttonGroup1.add(fiveRadioButton);
		fiveRadioButton.setText("5 Excellent");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(fourRadioButton).addComponent(fiveRadioButton).addComponent(twoRadioButton)
				.addComponent(threeRadioButton).addComponent(oneRadioButton));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addComponent(fiveRadioButton).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(fourRadioButton)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(threeRadioButton).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(twoRadioButton).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(oneRadioButton)));
	}// </editor-fold>//GEN-END:initComponents

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.ButtonGroup buttonGroup1;
	private javax.swing.JRadioButton fiveRadioButton;
	private javax.swing.JRadioButton fourRadioButton;
	private javax.swing.JRadioButton oneRadioButton;
	private javax.swing.JRadioButton threeRadioButton;
	private javax.swing.JRadioButton twoRadioButton;

	// End of variables declaration//GEN-END:variables
	@Override
	public int getGrade() {
		if (fiveRadioButton.isSelected()) {
			return 5;
		} else if (fourRadioButton.isSelected()) {
			return 4;
		} else if (threeRadioButton.isSelected()) {
			return 3;
		} else if (twoRadioButton.isSelected()) {
			return 2;
		} else if (oneRadioButton.isSelected()) {
			return 1;
		}
		return -1;
	}

	@Override
	public void reset() {
		buttonGroup1.clearSelection();
	}

	@Override
	public void enableOrDisableInputFields(boolean isEnable) {
		reset();
		fiveRadioButton.setEnabled(isEnable);
		fourRadioButton.setEnabled(isEnable);
		threeRadioButton.setEnabled(isEnable);
		twoRadioButton.setEnabled(isEnable);
		oneRadioButton.setEnabled(isEnable);
	}
}
