/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AdminSettingsForm.java
 *
 * Created on 4 Jun, 2011, 9:36:49 PM
 */
package com.bth.nrk.ui.admin;

import java.awt.event.ActionEvent;

import javax.swing.JOptionPane;
import javax.swing.JPanel;

import com.bth.excel.CreateExcelReport;
import com.bth.excel.CreateExcelReportPerVideo;
import com.bth.mos.MosConstants;

/**
 * 
 * @author Kalyan
 */
public class AdminSettingsForm extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private final CreateExcelReport createExcelReport = new CreateExcelReport();
	private final CreateExcelReportPerVideo createExcelReportPerVideo = new CreateExcelReportPerVideo();

	/** Creates new form AdminSettingsForm */
	public AdminSettingsForm() {
		initComponents();
		loadSurveyPanel(new NewSurveyPanel(this));
		setSize(MosConstants.xSize,MosConstants.ySize);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed"
	// <editor-fold defaultstate="collapsed"
	// <editor-fold defaultstate="collapsed"
	// <editor-fold defaultstate="collapsed"
	// <editor-fold defaultstate="collapsed"
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        topMenuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        newSurveyMenu = new javax.swing.JMenuItem();
        loadExistingSurveyMenu = new javax.swing.JMenuItem();
        surveyResultsMenu = new javax.swing.JMenu();
        resultPerUserMenu = new javax.swing.JMenuItem();
        resultPerVideoMenu = new javax.swing.JMenuItem();
        completeResultMenu = new javax.swing.JMenuItem();
        exitMenu = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        aboutMenu = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setUndecorated(true);

        fileMenu.setText("File");

        newSurveyMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        newSurveyMenu.setText("New Survey");
        newSurveyMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newSurveyMenuActionPerformed(evt);
            }
        });
        fileMenu.add(newSurveyMenu);

        loadExistingSurveyMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        loadExistingSurveyMenu.setText("Load Existing Survey");
        loadExistingSurveyMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadExistingSurveyMenuActionPerformed(evt);
            }
        });
        fileMenu.add(loadExistingSurveyMenu);

        surveyResultsMenu.setText("Survey Results");
        surveyResultsMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surveyResultsMenuActionPerformed(evt);
            }
        });

        resultPerUserMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        resultPerUserMenu.setText("Results per user");
        resultPerUserMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultPerUserMenuActionPerformed(evt);
            }
        });
        surveyResultsMenu.add(resultPerUserMenu);

        resultPerVideoMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK));
        resultPerVideoMenu.setText("Results Per video");
        resultPerVideoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	resultPerVideoMenuActionPerformed(evt);
            }
        });
        surveyResultsMenu.add(resultPerVideoMenu);

        completeResultMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK));
        completeResultMenu.setText("Complete Results");
        completeResultMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	completeResultMenuActionPerformed(evt);
            }
        });
        surveyResultsMenu.add(completeResultMenu);

        fileMenu.add(surveyResultsMenu);

        exitMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        exitMenu.setText("Exit");
        exitMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenu);

        topMenuBar.add(fileMenu);

        jMenu3.setText("Help");

        aboutMenu.setText("About");
        aboutMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuActionPerformed(evt);
            }
        });
        jMenu3.add(aboutMenu);

        topMenuBar.add(jMenu3);

        setJMenuBar(topMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 641, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 532, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        /**
         * This method to process the action to be performed if Results menu is pressed.
         */	
    protected void surveyResultsMenuActionPerformed(ActionEvent evt) {
		System.out.println(evt.getActionCommand());
	}

        /**
         * This method to process the action to be performed if about menu is pressed.
         */
	private void aboutMenuActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_aboutMenuActionPerformed
		new AboutDialog(this, true).setVisible(true);
	}// GEN-LAST:event_aboutMenuActionPerformed

	protected void resultPerVideoMenuActionPerformed(ActionEvent evt) {
		try {
			String result = createExcelReportPerVideo.createExcelReportPerVideo();
			JOptionPane.showMessageDialog(null, result);
		} catch (Exception e) {
			// e.printStackTrace();
			JOptionPane.showMessageDialog(null, e.getLocalizedMessage());
		}

	}

        /**
         * This method to generate complete results in excel report after result menu is pressed.
         */
	protected void completeResultMenuActionPerformed(ActionEvent evt) {
		try {
			String result = createExcelReport.createCompleteExcelReport();
			JOptionPane.showMessageDialog(null, result);
		} catch (Exception e) {
			// e.printStackTrace();
			JOptionPane.showMessageDialog(null, e.getLocalizedMessage());
		}
	}

        /**
         * This method to generate  results per user in excel report after (results per user) menu is pressed.
         */
	private void resultPerUserMenuActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_resultPerUserMenuActionPerformed
		try {
			String result = createExcelReport.createExcelReportPerUser();
			JOptionPane.showMessageDialog(null, result);
		} catch (Exception e) {
			// e.printStackTrace();
			JOptionPane.showMessageDialog(null, e.getLocalizedMessage());
		}
	}// GEN-LAST:event_resultPerUserMenuActionPerformed
        /**
         * This method to present the new survey panel if the NewSurvey menu is pressed
         * loadSurveyPanel is defined separately 
         */ 
	private void newSurveyMenuActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_newSurveyMenuActionPerformed
		loadSurveyPanel(new NewSurveyPanel(this));
	}// GEN-LAST:event_newSurveyMenuActionPerformed

        /**
         * This method to present the Existing survey panel if the NewSurvey menu is pressed
         * loadSurveyPanel is defined separately 
         */ 
        
	private void loadExistingSurveyMenuActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_loadExistingSurveyMenuActionPerformed
		loadSurveyPanel(new ExistingSurveyScreen(this));
	}// GEN-LAST:event_loadExistingSurveyMenuActionPerformed

        /**
         * If exit menu is selected, this method governs to close the application 
         */ 
	private void exitMenuActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_exitMenuActionPerformed
		System.exit(0);
	}// GEN-LAST:event_exitMenuActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenu;
    private javax.swing.JMenuItem completeResultMenu;
    private javax.swing.JMenuItem exitMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem loadExistingSurveyMenu;
    private javax.swing.JMenuItem newSurveyMenu;
    private javax.swing.JMenuItem resultPerUserMenu;
    private javax.swing.JMenuItem resultPerVideoMenu;
    private javax.swing.JMenu surveyResultsMenu;
    private javax.swing.JMenuBar topMenuBar;
    // End of variables declaration//GEN-END:variables

	private void loadSurveyPanel(final JPanel panel) {
		panel.setOpaque(true);
		panel.setSize(MosConstants.xSize,MosConstants.ySize);
		this.setContentPane(panel);
		pack();
	}
}
