/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewSurveyPanel.java
 *
 * Created on 4 Jun, 2011, 10:00:41 PM
 */
package com.bth.nrk.ui.admin;

import java.awt.event.ActionEvent;
import java.util.List;

import javax.swing.JOptionPane;

import com.bth.mos.MosConstants;
import com.bth.mos.manager.AdminSettingsManager;
import com.bth.mos.manager.SurveyDetails;
import com.bth.mos.persistence.entity.BinaryScale;
import com.bth.mos.persistence.entity.CustomScale;
import com.bth.mos.persistence.entity.Survey;
import com.bth.mos.persistence.entity.Survey.ScaleType;
import com.bth.mos.persistence.entity.Timer;
import com.bth.mos.persistence.entity.Timer.TimerType;
import com.bth.nrk.main.MainScreen;

/**
 * 
 * @author Kalyan
 */
public class ExistingSurveyScreen extends javax.swing.JPanel {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private final AdminSettingsForm mAdminSettingsForm;
	private final AdminSettingsManager mAdminSettingsManager = new AdminSettingsManager();

	public ExistingSurveyScreen(AdminSettingsForm adminSettingsForm) {
		initComponents();
		loadAllSurveyNames();
		mAdminSettingsForm = adminSettingsForm;
		setPreferredSize(new java.awt.Dimension(MosConstants.xSize, MosConstants.ySize));
	}

	public ExistingSurveyScreen() {
		initComponents();
		mAdminSettingsForm = null;
	}

	private void loadAllSurveyNames() {
		try {
			List<String> surveyNameList = mAdminSettingsManager.findAllSurveys();
			surveyComboBox.removeAllItems();
			for (String surveyName : surveyNameList) {
				surveyComboBox.addItem(surveyName);
			}
			setAsCurrentSurvey();
		} catch (Exception e) {
			surveyComboBox.removeAllItems();
			JOptionPane.showMessageDialog(null, e.getLocalizedMessage());
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		okButton = new javax.swing.JButton();
		jLabel10 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jPanel2 = new javax.swing.JPanel();
		ituTimerRadioButton = new javax.swing.JRadioButton();
		defaultTimerRadioButton = new javax.swing.JRadioButton();
		customTimerRadioButton = new javax.swing.JRadioButton();
		jLabel11 = new javax.swing.JLabel();
		jLabel12 = new javax.swing.JLabel();
		jLabel13 = new javax.swing.JLabel();
		jLabel14 = new javax.swing.JLabel();
		jLabel15 = new javax.swing.JLabel();
		jLabel16 = new javax.swing.JLabel();
		jLabel17 = new javax.swing.JLabel();
		jLabel18 = new javax.swing.JLabel();
		jLabel19 = new javax.swing.JLabel();
		ituTimerT1TextField = new javax.swing.JTextField();
		ituTimerT2TextField = new javax.swing.JTextField();
		customTimerT2TextField = new javax.swing.JTextField();
		customTimerT3TextField = new javax.swing.JTextField();
		ituTimerT3TextField = new javax.swing.JTextField();
		customTimerT1TextField = new javax.swing.JTextField();
		defaultTimerT2TextField = new javax.swing.JTextField();
		defaultTimerT3TextField = new javax.swing.JTextField();
		loadSurveyButton = new javax.swing.JButton();
		startSurveyButton = new javax.swing.JButton();
		videoLocation = new javax.swing.JTextField();
		deleteSurveyButton = new javax.swing.JButton();
		surveyComboBox = new javax.swing.JComboBox();
		jPanel1 = new javax.swing.JPanel();
		customScale = new javax.swing.JRadioButton();
		customScaleMaxTextField = new javax.swing.JTextField();
		customScaleMidTextField = new javax.swing.JTextField();
		customScaleMinTextField = new javax.swing.JTextField();
		cRadioButton3 = new javax.swing.JRadioButton();
		cRadioButton2 = new javax.swing.JRadioButton();
		cRadioButton1 = new javax.swing.JRadioButton();
		binaryScale = new javax.swing.JRadioButton();
		binaryScaleNegativeTextField = new javax.swing.JTextField();
		binaryScalePositiveTextField = new javax.swing.JTextField();
		bRadioButton1 = new javax.swing.JRadioButton();
		bRadioButton2 = new javax.swing.JRadioButton();
		fivePointScale = new javax.swing.JRadioButton();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();
		jSlider1 = new javax.swing.JSlider();
		jLabel7 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		hundredPointScale = new javax.swing.JRadioButton();
		jLabel4 = new javax.swing.JLabel();
		qualityRadioButton = new javax.swing.JRadioButton();
		impairmentRadioButton = new javax.swing.JRadioButton();

		okButton.setFont(new java.awt.Font("Tahoma", 1, 12));
		okButton.setText("OK");
		okButton.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				okButtonActionPerformed(evt);
			}
		});

		jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12));
		jLabel10.setText("Video Location:");

		jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12));
		jLabel8.setText("Name of the survey:");

		jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Time Elapse Settings in seconds"));

		ituTimerRadioButton.setFont(new java.awt.Font("Tahoma", 1, 12));
		ituTimerRadioButton.setText("ITU Time Elapse");
		ituTimerRadioButton.setEnabled(false);
		ituTimerRadioButton.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				ituTimerRadioButtonActionPerformed(evt);
			}
		});

		defaultTimerRadioButton.setFont(new java.awt.Font("Tahoma", 1, 12));
		defaultTimerRadioButton.setText("Default TIme Elapse");
		defaultTimerRadioButton.setEnabled(false);
		defaultTimerRadioButton.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				defaultTimerRadioButtonActionPerformed(evt);
			}
		});

		customTimerRadioButton.setFont(new java.awt.Font("Tahoma", 1, 12));
		customTimerRadioButton.setText("Custom Time Elaspe");
		customTimerRadioButton.setEnabled(false);
		customTimerRadioButton.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				customTimerRadioButtonActionPerformed(evt);
			}
		});

		jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12));
		jLabel11.setText("Video Time T1 ");

		jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12));
		jLabel12.setText("Video Time T1 ");

		jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12));
		jLabel13.setText("Pause Time T3 ");

		jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12));
		jLabel14.setText("Grade Time T2 ");

		jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12));
		jLabel15.setText("Grade Time T2 ");

		jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12));
		jLabel16.setText("Pause Time T3 ");

		jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12));
		jLabel17.setText("Grade Time T2 ");

		jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12));
		jLabel18.setText("Pause Time T3 ");

		jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12));
		jLabel19.setText("Play full video");

		ituTimerT1TextField.setEditable(false);
		ituTimerT1TextField.setText("10");
		ituTimerT1TextField.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				ituTimerT1TextFieldActionPerformed(evt);
			}
		});

		ituTimerT2TextField.setEditable(false);
		ituTimerT2TextField.setText("15");

		customTimerT2TextField.setEditable(false);
		customTimerT2TextField.setText("10");

		customTimerT3TextField.setEditable(false);
		customTimerT3TextField.setText("5");

		ituTimerT3TextField.setEditable(false);
		ituTimerT3TextField.setText("5");
		ituTimerT3TextField.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				ituTimerT3TextFieldActionPerformed(evt);
			}
		});

		customTimerT1TextField.setEditable(false);
		customTimerT1TextField.setText("10");

		defaultTimerT2TextField.setEditable(false);
		defaultTimerT2TextField.setText("10");

		defaultTimerT3TextField.setEditable(false);
		defaultTimerT3TextField.setText("5");

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel2Layout
						.createSequentialGroup()
						.addGroup(
								jPanel2Layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(
												jPanel2Layout
														.createSequentialGroup()
														.addGroup(
																jPanel2Layout
																		.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																		.addGroup(
																				jPanel2Layout
																						.createSequentialGroup()
																						.addContainerGap()
																						.addComponent(jLabel12)
																						.addGap(6, 6, 6)
																						.addComponent(ituTimerT1TextField, javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addGap(45, 45, 45)
																						.addComponent(jLabel11)
																						.addGap(5, 5, 5)
																						.addComponent(customTimerT1TextField, javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGroup(
																				jPanel2Layout.createSequentialGroup().addGap(10, 10, 10).addComponent(ituTimerRadioButton)
																						.addGap(18, 18, 18).addComponent(customTimerRadioButton)))
														.addGap(28, 28, 28)
														.addGroup(
																jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(defaultTimerRadioButton)
																		.addComponent(jLabel19)))
										.addGroup(
												jPanel2Layout
														.createSequentialGroup()
														.addContainerGap()
														.addComponent(jLabel14)
														.addGap(5, 5, 5)
														.addComponent(ituTimerT2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGap(45, 45, 45)
														.addComponent(jLabel15)
														.addGap(4, 4, 4)
														.addComponent(customTimerT2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGap(42, 42, 42)
														.addComponent(jLabel17)
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(defaultTimerT2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(
												jPanel2Layout
														.createSequentialGroup()
														.addContainerGap()
														.addComponent(jLabel13)
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(ituTimerT3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGap(45, 45, 45)
														.addComponent(jLabel16)
														.addGap(3, 3, 3)
														.addComponent(customTimerT3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGap(42, 42, 42)
														.addComponent(jLabel18)
														.addGap(2, 2, 2)
														.addComponent(defaultTimerT3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))).addContainerGap(142, Short.MAX_VALUE)));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel2Layout
						.createSequentialGroup()
						.addGroup(
								jPanel2Layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(
												jPanel2Layout
														.createSequentialGroup()
														.addContainerGap()
														.addGroup(
																jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(ituTimerRadioButton)
																		.addComponent(customTimerRadioButton).addComponent(defaultTimerRadioButton))
														.addGap(18, 18, 18)
														.addGroup(
																jPanel2Layout
																		.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																		.addGroup(
																				jPanel2Layout
																						.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(customTimerT1TextField, javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(jLabel11))
																		.addComponent(ituTimerT1TextField, javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(jLabel12)
																		.addGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING,
																				jPanel2Layout
																						.createSequentialGroup()
																						.addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 15,
																								javax.swing.GroupLayout.PREFERRED_SIZE).addGap(5, 5, 5))))
										.addGroup(
												jPanel2Layout
														.createSequentialGroup()
														.addGap(81, 81, 81)
														.addGroup(
																jPanel2Layout
																		.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																		.addGroup(
																				jPanel2Layout
																						.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(jLabel17)
																						.addComponent(defaultTimerT2TextField, javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGroup(
																				jPanel2Layout
																						.createSequentialGroup()
																						.addGap(5, 5, 5)
																						.addGroup(
																								jPanel2Layout
																										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																										.addComponent(jLabel15)
																										.addComponent(customTimerT2TextField,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												javax.swing.GroupLayout.PREFERRED_SIZE)))
																		.addGroup(
																				jPanel2Layout
																						.createSequentialGroup()
																						.addGap(5, 5, 5)
																						.addGroup(
																								jPanel2Layout
																										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																										.addComponent(ituTimerT2TextField, javax.swing.GroupLayout.PREFERRED_SIZE,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jLabel14))))))
						.addGap(18, 18, 18)
						.addGroup(
								jPanel2Layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(
												jPanel2Layout
														.createSequentialGroup()
														.addGap(3, 3, 3)
														.addGroup(
																jPanel2Layout
																		.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																		.addComponent(jLabel18)
																		.addGroup(
																				jPanel2Layout
																						.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(jLabel16)
																						.addComponent(customTimerT3TextField, javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addComponent(ituTimerT3TextField, javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(jLabel13)))
										.addComponent(defaultTimerT3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)).addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		loadSurveyButton.setText("Load Survey");
		loadSurveyButton.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				loadSurveyButtonActionPerformed(evt);
			}
		});

		startSurveyButton.setText("StartSurvey");
		startSurveyButton.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				startSurveyButtonActionPerformed(evt);
			}
		});

		videoLocation.setEditable(false);

		deleteSurveyButton.setText("DeleteSurvey");
		deleteSurveyButton.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				deleteSurveyButtonActionPerformed(evt);
			}
		});

		surveyComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

		jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Scale", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));

		customScale.setFont(new java.awt.Font("Tahoma", 1, 12));
		customScale.setText("Custom scale");
		customScale.setEnabled(false);
		customScale.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				customScaleActionPerformed(evt);
			}
		});

		customScaleMaxTextField.setEditable(false);
		customScaleMaxTextField.setText("Best");

		customScaleMidTextField.setEditable(false);
		customScaleMidTextField.setText("Good");

		customScaleMinTextField.setEditable(false);
		customScaleMinTextField.setText("Bad");

		cRadioButton3.setEnabled(false);

		cRadioButton2.setEnabled(false);
		cRadioButton2.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				cRadioButton2ActionPerformed(evt);
			}
		});

		cRadioButton1.setEnabled(false);

		binaryScale.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		binaryScale.setText("Binary scale");
		binaryScale.setEnabled(false);
		binaryScale.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				binaryScaleActionPerformed(evt);
			}
		});

		binaryScaleNegativeTextField.setEditable(false);
		binaryScaleNegativeTextField.setText("Un-acceptable");

		binaryScalePositiveTextField.setEditable(false);
		binaryScalePositiveTextField.setText("Acceptable");

		bRadioButton1.setText("1");
		bRadioButton1.setEnabled(false);

		bRadioButton2.setText("0");
		bRadioButton2.setEnabled(false);
		bRadioButton2.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				bRadioButton2ActionPerformed(evt);
			}
		});

		fivePointScale.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		fivePointScale.setText("MOS 5 point scale");
		fivePointScale.setEnabled(false);
		fivePointScale.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				fivePointScaleActionPerformed(evt);
			}
		});

		jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
		jLabel2.setText("4");

		jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12));
		jLabel3.setText("3");

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12));
		jLabel1.setText("5");

		jSlider1.setOrientation(javax.swing.JSlider.VERTICAL);
		jSlider1.setPaintLabels(true);
		jSlider1.setEnabled(false);

		jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12));
		jLabel7.setText("0");

		jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12));
		jLabel6.setText("100");

		jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12));
		jLabel5.setText("1");

		hundredPointScale.setFont(new java.awt.Font("Tahoma", 1, 12));
		hundredPointScale.setText("100 point scale");
		hundredPointScale.setEnabled(false);
		hundredPointScale.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				hundredPointScaleActionPerformed(evt);
			}
		});

		jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12));
		jLabel4.setText("2");

		qualityRadioButton.setText("Quality");
		qualityRadioButton.setEnabled(false);
		qualityRadioButton.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				qualityRadioButtonActionPerformed(evt);
			}
		});

		impairmentRadioButton.setText("Impairment");
		impairmentRadioButton.setEnabled(false);
		impairmentRadioButton.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				impairmentRadioButtonActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						jPanel1Layout
								.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(hundredPointScale)
												.addGroup(
														jPanel1Layout
																.createSequentialGroup()
																.addGroup(
																		jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addComponent(jLabel7)
																				.addComponent(jLabel6))
																.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(18, 18, 18)
																.addGroup(
																		jPanel1Layout
																				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
																						Short.MAX_VALUE)
																				.addComponent(jLabel2)
																				.addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
																						Short.MAX_VALUE)
																				.addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 16, Short.MAX_VALUE)
																				.addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16,
																						javax.swing.GroupLayout.PREFERRED_SIZE))))
								.addGap(6, 6, 6)
								.addGroup(
										jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(fivePointScale).addComponent(qualityRadioButton)
												.addComponent(impairmentRadioButton))
								.addGap(18, 18, 18)
								.addGroup(
										jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(binaryScale)
												.addGroup(
														jPanel1Layout
																.createSequentialGroup()
																.addGroup(
																		jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(bRadioButton1)
																				.addComponent(bRadioButton2))
																.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		jPanel1Layout
																				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(binaryScaleNegativeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 85,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(binaryScalePositiveTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
								.addGap(18, 18, 18)
								.addGroup(
										jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														jPanel1Layout
																.createSequentialGroup()
																.addGroup(
																		jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(cRadioButton1)
																				.addComponent(cRadioButton3).addComponent(cRadioButton2))
																.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
																				.addComponent(customScaleMinTextField).addComponent(customScaleMaxTextField)
																				.addComponent(customScaleMidTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)))
												.addComponent(customScale)).addGap(281, 281, 281)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						jPanel1Layout
								.createSequentialGroup()
								.addGroup(
										jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(hundredPointScale).addComponent(fivePointScale))
								.addGap(8, 8, 8)
								.addGroup(
										jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
												.addGroup(
														javax.swing.GroupLayout.Alignment.LEADING,
														jPanel1Layout.createSequentialGroup().addComponent(jLabel6)
																.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE).addComponent(jLabel7))
												.addGroup(
														javax.swing.GroupLayout.Alignment.LEADING,
														jPanel1Layout.createSequentialGroup().addComponent(jSlider1, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
																.addContainerGap())
												.addGroup(
														javax.swing.GroupLayout.Alignment.LEADING,
														jPanel1Layout
																.createSequentialGroup()
																.addGap(7, 7, 7)
																.addGroup(
																		jPanel1Layout
																				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																				.addGroup(
																						jPanel1Layout
																								.createSequentialGroup()
																								.addComponent(impairmentRadioButton)
																								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																								.addComponent(qualityRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23,
																										javax.swing.GroupLayout.PREFERRED_SIZE))
																				.addGroup(
																						jPanel1Layout
																								.createSequentialGroup()
																								.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
																										javax.swing.GroupLayout.PREFERRED_SIZE)
																								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
																										javax.swing.GroupLayout.PREFERRED_SIZE)
																								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
																										javax.swing.GroupLayout.PREFERRED_SIZE)
																								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																								.addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
																										javax.swing.GroupLayout.PREFERRED_SIZE)
																								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
																										javax.swing.GroupLayout.PREFERRED_SIZE))).addGap(27, 27, 27))))
				.addGroup(
						jPanel1Layout
								.createSequentialGroup()
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(binaryScale).addComponent(customScale))
								.addGap(18, 18, 18)
								.addGroup(
										jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														jPanel1Layout
																.createSequentialGroup()
																.addGroup(
																		jPanel1Layout
																				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
																				.addGroup(
																						jPanel1Layout
																								.createSequentialGroup()
																								.addComponent(cRadioButton1)
																								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
																								.addComponent(cRadioButton2))
																				.addGroup(
																						jPanel1Layout
																								.createSequentialGroup()
																								.addComponent(customScaleMaxTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
																										javax.swing.GroupLayout.DEFAULT_SIZE,
																										javax.swing.GroupLayout.PREFERRED_SIZE)
																								.addGap(6, 6, 6)
																								.addComponent(customScaleMidTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
																										javax.swing.GroupLayout.DEFAULT_SIZE,
																										javax.swing.GroupLayout.PREFERRED_SIZE)))
																.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		jPanel1Layout
																				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(customScaleMinTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(cRadioButton3)))
												.addGroup(
														jPanel1Layout.createSequentialGroup().addComponent(bRadioButton1)
																.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(bRadioButton2))
												.addGroup(
														jPanel1Layout
																.createSequentialGroup()
																.addComponent(binaryScalePositiveTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addComponent(binaryScaleNegativeTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 643, Short.MAX_VALUE)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(jLabel8)
																.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(surveyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(loadSurveyButton))
												.addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(jPanel1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addGroup(
														layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																.addGroup(
																		layout.createSequentialGroup()
																				.addComponent(jLabel10)
																				.addGap(18, 18, 18)
																				.addComponent(videoLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 391,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addGroup(
																		javax.swing.GroupLayout.Alignment.TRAILING,
																		layout.createSequentialGroup()
																				.addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																				.addComponent(startSurveyButton)
																				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																				.addComponent(deleteSurveyButton))))
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 544, Short.MAX_VALUE)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel8)
												.addComponent(surveyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(loadSurveyButton))
								.addGap(18, 18, 18)
								.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(25, 25, 25)
								.addGroup(
										layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel10)
												.addComponent(videoLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(okButton).addComponent(startSurveyButton)
												.addComponent(deleteSurveyButton)).addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
	}// </editor-fold>

	protected void qualityRadioButtonActionPerformed(ActionEvent evt) {
		// TODO Auto-generated method stub

	}

	protected void impairmentRadioButtonActionPerformed(ActionEvent evt) {
		// TODO Auto-generated method stub

	}

	protected void deleteSurveyButtonActionPerformed(ActionEvent evt) {
		try {
			mAdminSettingsManager.deleteSurveyByName(surveyComboBox.getSelectedItem().toString());
			JOptionPane.showMessageDialog(null, surveyComboBox.getSelectedItem().toString() + " Survey Deleted.");
			loadAllSurveyNames();
		} catch (Exception e) {
			JOptionPane.showMessageDialog(null, e.getLocalizedMessage());
		}

	}

	private void startSurveyButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_startSurveyButtonActionPerformed
		mAdminSettingsForm.setVisible(false);
		new MainScreen().setVisible(true);
	}// GEN-LAST:event_startSurveyButtonActionPerformed

	private void customScaleActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_customScaleActionPerformed
	}// GEN-LAST:event_customScaleActionPerformed

	private void cRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cRadioButton2ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_cRadioButton2ActionPerformed

	private void binaryScaleActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_binaryScaleActionPerformed
	}// GEN-LAST:event_binaryScaleActionPerformed

	private void bRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_bRadioButton2ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_bRadioButton2ActionPerformed

	private void fivePointScaleActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_fivePointScaleActionPerformed
	}// GEN-LAST:event_fivePointScaleActionPerformed

	private void hundredPointScaleActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_hundredPointScaleActionPerformed
	}// GEN-LAST:event_hundredPointScaleActionPerformed

	private void ituTimerRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ituTimerRadioButtonActionPerformed
	}// GEN-LAST:event_ituTimerRadioButtonActionPerformed

	private void defaultTimerRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_defaultTimerRadioButtonActionPerformed
	}// GEN-LAST:event_defaultTimerRadioButtonActionPerformed

	private void customTimerRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_customTimerRadioButtonActionPerformed
	}// GEN-LAST:event_customTimerRadioButtonActionPerformed

	private void ituTimerT1TextFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ituTimerT1TextFieldActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_ituTimerT1TextFieldActionPerformed

	private void ituTimerT3TextFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ituTimerT3TextFieldActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_ituTimerT3TextFieldActionPerformed

	private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_okButtonActionPerformed
		try {
			setAsCurrentSurvey();
			JOptionPane.showMessageDialog(null, surveyComboBox.getSelectedItem().toString() + " Survey loaded.");
			startSurveyButton.setEnabled(true);
		} catch (Exception e) {
			JOptionPane.showMessageDialog(null, e.getLocalizedMessage());
		}

	}// GEN-LAST:event_okButtonActionPerformed

	private void setAsCurrentSurvey() {
		Object selectedItem = surveyComboBox.getSelectedItem();
		if (selectedItem == null) {
			throw new UnsupportedOperationException("No surveys are found. Please create a new survey.");
		}
		String surveyName = surveyComboBox.getSelectedItem().toString();
		mAdminSettingsManager.setAsCurrentSurvey(surveyName);
	}

	private void loadSurveyButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_loadSurveyButtonActionPerformed
		try {
			loadSurvey();
			setAsCurrentSurvey();
		} catch (Exception e) {
			e.printStackTrace();
			JOptionPane.showMessageDialog(null, e.getLocalizedMessage());
		}
	}// GEN-LAST:event_loadSurveyButtonActionPerformed

	private void loadSurvey() {
		Object selectedItem = surveyComboBox.getSelectedItem();
		if (selectedItem == null) {
			throw new UnsupportedOperationException("No surveys are found. Please create a new survey.");
		}
		String surveyName = selectedItem.toString();

		SurveyDetails surveyDetails = mAdminSettingsManager.findSurveyByName(surveyName);
		Survey survey = surveyDetails.getSurvey();

		if (survey.getScaleType() == ScaleType.CONTINOUS_SCALE) {
			hundredPointScale.setSelected(true);
		} else if (survey.getScaleType() == ScaleType.FIVE_POINT_QUALITY_SCALE) {
			fivePointScale.setSelected(true);
			qualityRadioButton.setSelected(true);
			impairmentRadioButton.setSelected(false);
		} else if (survey.getScaleType() == ScaleType.FIVE_POINT_IMPAIRMENT_SCALE) {
			fivePointScale.setSelected(true);
			qualityRadioButton.setSelected(false);
			impairmentRadioButton.setSelected(true);
		} else if (survey.getScaleType() == ScaleType.BINARY_SCALE) {
			binaryScale.setSelected(true);
			BinaryScale binaryScale2 = surveyDetails.getBinaryScale();
			binaryScalePositiveTextField.setText(binaryScale2.getPositiveScale());
			binaryScaleNegativeTextField.setText(binaryScale2.getNegativeScale());
		} else if (survey.getScaleType() == ScaleType.CUSTOM_SCALE) {
			customScale.setSelected(true);
			CustomScale customScale2 = surveyDetails.getCustomScale();
			customScaleMaxTextField.setText(customScale2.getMaxScale());
			customScaleMidTextField.setText(customScale2.getMidScale());
			customScaleMinTextField.setText(customScale2.getMinScale());
		}

		Timer timer = surveyDetails.getTimer();
		String t1 = timer.getT1() + "";
		String t2 = timer.getT2() + "";
		String t3 = timer.getT3() + "";
		if (timer.getTimerType() == TimerType.ITUTIMER) {
			ituTimerRadioButton.setSelected(true);
			ituTimerT1TextField.setText(t1);
			ituTimerT2TextField.setText(t2);
			ituTimerT3TextField.setText(t3);
		} else if (timer.getTimerType() == TimerType.CUSTOMTIMER) {
			customTimerRadioButton.setSelected(true);
			customTimerT1TextField.setText(t1);
			customTimerT2TextField.setText(t2);
			customTimerT3TextField.setText(t3);

		} else if (timer.getTimerType() == TimerType.DEFAULTTIMER) {
			defaultTimerRadioButton.setSelected(true);
			defaultTimerT2TextField.setText(t2);
			defaultTimerT3TextField.setText(t3);
		}
		videoLocation.setText(survey.getVideoLocation());
	}

	// Variables declaration - do not modify
	private javax.swing.JRadioButton bRadioButton1;
	private javax.swing.JRadioButton bRadioButton2;
	private javax.swing.JRadioButton binaryScale;
	private javax.swing.JTextField binaryScaleNegativeTextField;
	private javax.swing.JTextField binaryScalePositiveTextField;
	private javax.swing.JRadioButton cRadioButton1;
	private javax.swing.JRadioButton cRadioButton2;
	private javax.swing.JRadioButton cRadioButton3;
	private javax.swing.JRadioButton customScale;
	private javax.swing.JTextField customScaleMaxTextField;
	private javax.swing.JTextField customScaleMidTextField;
	private javax.swing.JTextField customScaleMinTextField;
	private javax.swing.JRadioButton customTimerRadioButton;
	private javax.swing.JTextField customTimerT1TextField;
	private javax.swing.JTextField customTimerT2TextField;
	private javax.swing.JTextField customTimerT3TextField;
	private javax.swing.JRadioButton defaultTimerRadioButton;
	private javax.swing.JTextField defaultTimerT2TextField;
	private javax.swing.JTextField defaultTimerT3TextField;
	private javax.swing.JRadioButton fivePointScale;
	private javax.swing.JRadioButton hundredPointScale;
	private javax.swing.JRadioButton ituTimerRadioButton;
	private javax.swing.JTextField ituTimerT1TextField;
	private javax.swing.JTextField ituTimerT2TextField;
	private javax.swing.JTextField ituTimerT3TextField;
	private javax.swing.JButton deleteSurveyButton;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel15;
	private javax.swing.JLabel jLabel16;
	private javax.swing.JLabel jLabel17;
	private javax.swing.JLabel jLabel18;
	private javax.swing.JLabel jLabel19;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JSlider jSlider1;
	private javax.swing.JButton loadSurveyButton;
	private javax.swing.JButton okButton;
	private javax.swing.JButton startSurveyButton;
	private javax.swing.JComboBox surveyComboBox;
	private javax.swing.JTextField videoLocation;
	private javax.swing.JRadioButton impairmentRadioButton;
	private javax.swing.JRadioButton qualityRadioButton;
}
