/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewSurveyPanel.java
 *
 * Created on 4 Jun, 2011, 10:00:41 PM
 */
package com.bth.nrk.ui.admin;

import java.awt.event.ActionEvent;
import java.io.File;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

import com.bth.mos.MosConstants;
import com.bth.mos.manager.AdminSettingsManager;
import com.bth.mos.manager.CommonUtils;
import com.bth.mos.persistence.entity.BinaryScale;
import com.bth.mos.persistence.entity.CustomScale;
import com.bth.mos.persistence.entity.Survey;
import com.bth.mos.persistence.entity.Survey.ScaleType;
import com.bth.mos.persistence.entity.Timer;
import com.bth.nrk.main.MainScreen;

/**
 * 
 * @author Kalyan
 */
public class NewSurveyPanel extends javax.swing.JPanel {

	/**
	 * ok
	 */
	private static final long serialVersionUID = 1L;
	private final AdminSettingsManager mAdminSettingsManager = new AdminSettingsManager();
	private final AdminSettingsForm mAdminSettingsForm;

	public NewSurveyPanel(AdminSettingsForm adminSettingsForm) {
		initComponents();
		mAdminSettingsForm = adminSettingsForm;
		ituTimerT1TextField.setText(CommonUtils.itutimerT1);
		ituTimerT2TextField.setText(CommonUtils.itutimerT2);
		ituTimerT3TextField.setText(CommonUtils.itutimerT3);
		setPreferredSize(new java.awt.Dimension(MosConstants.xSize, MosConstants.ySize));
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed"
	// <editor-fold defaultstate="collapsed"
	// <editor-fold defaultstate="collapsed"
	// <editor-fold defaultstate="collapsed"
	// <editor-fold defaultstate="collapsed"
	// <editor-fold defaultstate="collapsed"
	// <editor-fold defaultstate="collapsed"
	// <editor-fold defaultstate="collapsed"
	// <editor-fold defaultstate="collapsed"
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		buttonGroup1 = new javax.swing.ButtonGroup();
		buttonGroup2 = new javax.swing.ButtonGroup();
		buttonGroup3 = new javax.swing.ButtonGroup();
		resetButton = new javax.swing.JButton();
		startSurveyButton = new javax.swing.JButton();
		fileChooserButton = new javax.swing.JButton();
		surveyNameTextField = new javax.swing.JTextField();
		jLabel8 = new javax.swing.JLabel();
		jPanel1 = new javax.swing.JPanel();
		customScale = new javax.swing.JRadioButton();
		customScaleMaxTextField = new javax.swing.JTextField();
		customScaleMidTextField = new javax.swing.JTextField();
		customScaleMinTextField = new javax.swing.JTextField();
		cRadioButton3 = new javax.swing.JRadioButton();
		cRadioButton2 = new javax.swing.JRadioButton();
		cRadioButton1 = new javax.swing.JRadioButton();
		binaryScale = new javax.swing.JRadioButton();
		binaryScaleNegativeTextField = new javax.swing.JTextField();
		binaryScalePositiveTextField = new javax.swing.JTextField();
		bRadioButton1 = new javax.swing.JRadioButton();
		bRadioButton2 = new javax.swing.JRadioButton();
		qualityRadioButton = new javax.swing.JRadioButton();
		impairmentRadioButton = new javax.swing.JRadioButton();
		fivePointScale = new javax.swing.JRadioButton();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();
		jSlider1 = new javax.swing.JSlider();
		jLabel7 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		hundredPointScale = new javax.swing.JRadioButton();
		jLabel4 = new javax.swing.JLabel();
		jPanel2 = new javax.swing.JPanel();
		ituTimerRadioButton = new javax.swing.JRadioButton();
		defaultTimerRadioButton = new javax.swing.JRadioButton();
		customTimerRadioButton = new javax.swing.JRadioButton();
		jLabel11 = new javax.swing.JLabel();
		jLabel12 = new javax.swing.JLabel();
		jLabel13 = new javax.swing.JLabel();
		jLabel14 = new javax.swing.JLabel();
		jLabel15 = new javax.swing.JLabel();
		jLabel16 = new javax.swing.JLabel();
		jLabel17 = new javax.swing.JLabel();
		jLabel18 = new javax.swing.JLabel();
		jLabel19 = new javax.swing.JLabel();
		ituTimerT1TextField = new javax.swing.JTextField();
		ituTimerT2TextField = new javax.swing.JTextField();
		customTimerT2TextField = new javax.swing.JTextField();
		customTimerT3TextField = new javax.swing.JTextField();
		ituTimerT3TextField = new javax.swing.JTextField();
		customTimerT1TextField = new javax.swing.JTextField();
		defaultTimerT2TextField = new javax.swing.JTextField();
		defaultTimerT3TextField = new javax.swing.JTextField();
		okButton = new javax.swing.JButton();
		jLabel10 = new javax.swing.JLabel();
		videoLocation = new javax.swing.JTextField();

		setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
		setPreferredSize(new java.awt.Dimension(649, 565));

		resetButton.setFont(new java.awt.Font("Tahoma", 1, 12));
		resetButton.setText("Reset");
		resetButton.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				resetButtonActionPerformed(evt);
			}
		});

		startSurveyButton.setFont(new java.awt.Font("Tahoma", 1, 12));
		startSurveyButton.setText("Start Survey");
		startSurveyButton.setEnabled(false);
		startSurveyButton.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				startSurveyButtonActionPerformed(evt);
			}
		});

		fileChooserButton.setFont(new java.awt.Font("Tahoma", 1, 12));
		fileChooserButton.setText("....");
		fileChooserButton.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				fileChooserButtonActionPerformed(evt);
			}
		});

		surveyNameTextField.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				surveyNameTextFieldActionPerformed(evt);
			}
		});

		jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12));
		jLabel8.setText("Name of the survey:");

		jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Scale", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));

		buttonGroup1.add(customScale);
		customScale.setFont(new java.awt.Font("Tahoma", 1, 12));
		customScale.setText("Custom scale");
		customScale.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				customScaleActionPerformed(evt);
			}
		});

		customScaleMaxTextField.setEditable(false);
		customScaleMaxTextField.setText("Best");

		customScaleMidTextField.setEditable(false);
		customScaleMidTextField.setText("Good");

		customScaleMinTextField.setEditable(false);
		customScaleMinTextField.setText("Bad");

		cRadioButton3.setEnabled(false);

		cRadioButton2.setEnabled(false);
		cRadioButton2.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				cRadioButton2ActionPerformed(evt);
			}
		});

		cRadioButton1.setEnabled(false);

		buttonGroup1.add(binaryScale);
		binaryScale.setFont(new java.awt.Font("Tahoma", 1, 12));
		binaryScale.setText("Binary scale");
		binaryScale.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				binaryScaleActionPerformed(evt);
			}
		});

		binaryScaleNegativeTextField.setEditable(false);
		binaryScaleNegativeTextField.setText("Un-acceptable");

		binaryScalePositiveTextField.setEditable(false);
		binaryScalePositiveTextField.setText("Acceptable");

		bRadioButton1.setText("1");
		bRadioButton1.setEnabled(false);

		bRadioButton2.setText("0");
		bRadioButton2.setEnabled(false);
		bRadioButton2.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				bRadioButton2ActionPerformed(evt);
			}
		});

		buttonGroup3.add(qualityRadioButton);
		qualityRadioButton.setText("Quality");
		qualityRadioButton.setEnabled(false);
		qualityRadioButton.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				qualityRadioButtonActionPerformed(evt);
			}
		});

		buttonGroup3.add(impairmentRadioButton);
		impairmentRadioButton.setText("Impairment");
		impairmentRadioButton.setEnabled(false);
		impairmentRadioButton.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				impairmentRadioButtonActionPerformed(evt);
			}
		});

		buttonGroup1.add(fivePointScale);
		fivePointScale.setFont(new java.awt.Font("Tahoma", 1, 12));
		fivePointScale.setText("MOS 5 point scale");
		fivePointScale.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				fivePointScaleActionPerformed(evt);
			}
		});

		jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
		jLabel2.setText("4");

		jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12));
		jLabel3.setText("3");

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12));
		jLabel1.setText("5");

		jSlider1.setOrientation(javax.swing.JSlider.VERTICAL);
		jSlider1.setPaintLabels(true);
		jSlider1.setEnabled(false);

		jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12));
		jLabel7.setText("0");

		jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12));
		jLabel6.setText("100");

		jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12));
		jLabel5.setText("1");

		buttonGroup1.add(hundredPointScale);
		hundredPointScale.setFont(new java.awt.Font("Tahoma", 1, 12));
		hundredPointScale.setText("Continuous Scale");
		hundredPointScale.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				hundredPointScaleActionPerformed(evt);
			}
		});

		jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12));
		jLabel4.setText("2");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				jPanel1Layout
						.createSequentialGroup()
						.addContainerGap()
						.addGroup(
								jPanel1Layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(hundredPointScale)
										.addGroup(
												jPanel1Layout
														.createSequentialGroup()
														.addGap(8, 8, 8)
														.addGroup(
																jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addComponent(jLabel6)
																		.addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE))
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
														.addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGap(10, 10, 10)
														.addGroup(
																jPanel1Layout
																		.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																		.addComponent(jLabel2)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
																						.addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
																						.addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
						.addGap(6, 6, 6)
						.addGroup(
								jPanel1Layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addComponent(fivePointScale)
										.addGroup(
												jPanel1Layout
														.createSequentialGroup()
														.addGap(21, 21, 21)
														.addGroup(
																jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(qualityRadioButton)
																		.addComponent(impairmentRadioButton))))
						.addGap(18, 18, 18)
						.addGroup(
								jPanel1Layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(binaryScale)
										.addGroup(
												jPanel1Layout
														.createSequentialGroup()
														.addGroup(
																jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(bRadioButton1)
																		.addComponent(bRadioButton2))
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addGroup(
																jPanel1Layout
																		.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																		.addComponent(binaryScaleNegativeTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(binaryScalePositiveTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
						.addGap(18, 18, 18)
						.addGroup(
								jPanel1Layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(
												jPanel1Layout
														.createSequentialGroup()
														.addGroup(
																jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(cRadioButton1)
																		.addComponent(cRadioButton3).addComponent(cRadioButton2))
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addGroup(
																jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
																		.addComponent(customScaleMinTextField).addComponent(customScaleMaxTextField)
																		.addComponent(customScaleMidTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)))
										.addComponent(customScale)).addGap(281, 281, 281)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(hundredPointScale).addComponent(fivePointScale))
																		.addGap(8, 8, 8)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addComponent(impairmentRadioButton)
																										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																										.addComponent(qualityRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE,
																												23, javax.swing.GroupLayout.PREFERRED_SIZE))
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addGap(7, 7, 7)
																										.addGroup(
																												jPanel1Layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING, false)
																														.addGroup(
																																jPanel1Layout
																																		.createSequentialGroup()
																																		.addComponent(
																																				jLabel1,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				14,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addGap(15, 15, 15)
																																		.addComponent(
																																				jLabel2,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				14,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																																		.addComponent(
																																				jLabel3,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				14,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																																		.addComponent(
																																				jLabel4,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				14,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																																		.addComponent(
																																				jLabel5,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				14,
																																				javax.swing.GroupLayout.PREFERRED_SIZE))
																														.addComponent(jSlider1,
																																javax.swing.GroupLayout.PREFERRED_SIZE, 127,
																																javax.swing.GroupLayout.PREFERRED_SIZE)
																														.addGroup(
																																jPanel1Layout
																																		.createSequentialGroup()
																																		.addComponent(jLabel6)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																																				javax.swing.GroupLayout.DEFAULT_SIZE,
																																				Short.MAX_VALUE)
																																		.addComponent(jLabel7).addGap(8, 8, 8))))))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(binaryScale).addComponent(customScale))
																		.addGap(18, 18, 18)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addGroup(
																												jPanel1Layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING, false)
																														.addGroup(
																																jPanel1Layout
																																		.createSequentialGroup()
																																		.addComponent(cRadioButton1)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																																				javax.swing.GroupLayout.DEFAULT_SIZE,
																																				Short.MAX_VALUE)
																																		.addComponent(cRadioButton2))
																														.addGroup(
																																jPanel1Layout
																																		.createSequentialGroup()
																																		.addComponent(
																																				customScaleMaxTextField,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				javax.swing.GroupLayout.DEFAULT_SIZE,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addGap(6, 6, 6)
																																		.addComponent(
																																				customScaleMidTextField,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				javax.swing.GroupLayout.DEFAULT_SIZE,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)))
																										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addGroup(
																												jPanel1Layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addComponent(customScaleMinTextField,
																																javax.swing.GroupLayout.PREFERRED_SIZE,
																																javax.swing.GroupLayout.DEFAULT_SIZE,
																																javax.swing.GroupLayout.PREFERRED_SIZE)
																														.addComponent(cRadioButton3)))
																						.addGroup(
																								jPanel1Layout.createSequentialGroup().addComponent(bRadioButton1)
																										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																										.addComponent(bRadioButton2))
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addComponent(binaryScalePositiveTextField,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																										.addComponent(binaryScaleNegativeTextField,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												javax.swing.GroupLayout.PREFERRED_SIZE))))).addContainerGap()));

		jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Time Elapse Settings in seconds"));

		buttonGroup2.add(ituTimerRadioButton);
		ituTimerRadioButton.setFont(new java.awt.Font("Tahoma", 1, 12));
		ituTimerRadioButton.setText("ITU Time Elapse");
		ituTimerRadioButton.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				ituTimerRadioButtonActionPerformed(evt);
			}
		});

		buttonGroup2.add(defaultTimerRadioButton);
		defaultTimerRadioButton.setFont(new java.awt.Font("Tahoma", 1, 12));
		defaultTimerRadioButton.setText("Full Length Video");
		defaultTimerRadioButton.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				defaultTimerRadioButtonActionPerformed(evt);
			}
		});

		buttonGroup2.add(customTimerRadioButton);
		customTimerRadioButton.setFont(new java.awt.Font("Tahoma", 1, 12));
		customTimerRadioButton.setText("Custom Time Elaspe");
		customTimerRadioButton.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				customTimerRadioButtonActionPerformed(evt);
			}
		});

		jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12));
		jLabel11.setText("Video Time T1 ");

		jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12));
		jLabel12.setText("Video Time T1 ");

		jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12));
		jLabel13.setText("Pause Time T3 ");

		jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12));
		jLabel14.setText("Grade Time T2 ");

		jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12));
		jLabel15.setText("Grade Time T2 ");

		jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12));
		jLabel16.setText("Pause Time T3 ");

		jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12));
		jLabel17.setText("Grade Time T2 ");

		jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12));
		jLabel18.setText("Pause Time T3 ");

		jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12));
		jLabel19.setText("Play full video");

		ituTimerT1TextField.setEditable(false);
		ituTimerT1TextField.setText("10");
		ituTimerT1TextField.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				ituTimerT1TextFieldActionPerformed(evt);
			}
		});

		ituTimerT2TextField.setEditable(false);
		ituTimerT2TextField.setText("15");

		customTimerT2TextField.setEditable(false);
		customTimerT2TextField.setText("10");

		customTimerT3TextField.setEditable(false);
		customTimerT3TextField.setText("5");

		ituTimerT3TextField.setEditable(false);
		ituTimerT3TextField.setText("5");
		ituTimerT3TextField.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				ituTimerT3TextFieldActionPerformed(evt);
			}
		});

		customTimerT1TextField.setEditable(false);
		customTimerT1TextField.setText("10");

		defaultTimerT2TextField.setEditable(false);
		defaultTimerT2TextField.setText("10");

		defaultTimerT3TextField.setEditable(false);
		defaultTimerT3TextField.setText("5");

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel2Layout
						.createSequentialGroup()
						.addGroup(
								jPanel2Layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(
												jPanel2Layout
														.createSequentialGroup()
														.addContainerGap()
														.addGroup(
																jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLabel14)
																		.addComponent(jLabel13))
														.addGap(12, 12, 12)
														.addGroup(
																jPanel2Layout
																		.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
																		.addGroup(
																				jPanel2Layout
																						.createSequentialGroup()
																						.addComponent(ituTimerT2TextField, javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addGap(45, 45, 45).addComponent(jLabel15))
																		.addGroup(
																				jPanel2Layout
																						.createSequentialGroup()
																						.addComponent(ituTimerT3TextField, javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(jLabel16)))
														.addGap(18, 18, 18)
														.addGroup(
																jPanel2Layout
																		.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																		.addComponent(customTimerT3TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
																		.addComponent(customTimerT2TextField, javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addGroup(
												jPanel2Layout
														.createSequentialGroup()
														.addGroup(
																jPanel2Layout
																		.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																		.addGroup(
																				jPanel2Layout
																						.createSequentialGroup()
																						.addContainerGap()
																						.addComponent(jLabel12)
																						.addGap(12, 12, 12)
																						.addComponent(ituTimerT1TextField, javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGroup(jPanel2Layout.createSequentialGroup().addGap(10, 10, 10).addComponent(ituTimerRadioButton)))
														.addGap(46, 46, 46)
														.addGroup(
																jPanel2Layout
																		.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																		.addComponent(customTimerRadioButton)
																		.addGroup(
																				jPanel2Layout
																						.createSequentialGroup()
																						.addComponent(jLabel11)
																						.addGap(18, 18, 18)
																						.addComponent(customTimerT1TextField, javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
						.addGap(33, 33, 33)
						.addGroup(
								jPanel2Layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jLabel19)
										.addGroup(
												jPanel2Layout
														.createSequentialGroup()
														.addComponent(jLabel18)
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(defaultTimerT3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addComponent(defaultTimerRadioButton)
										.addGroup(
												jPanel2Layout
														.createSequentialGroup()
														.addComponent(jLabel17)
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(defaultTimerT2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))).addContainerGap(320, Short.MAX_VALUE)));

		jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] { customTimerT1TextField, customTimerT2TextField, customTimerT3TextField,
				defaultTimerT2TextField, defaultTimerT3TextField, ituTimerT1TextField, ituTimerT2TextField, ituTimerT3TextField });

		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel2Layout
						.createSequentialGroup()
						.addGroup(
								jPanel2Layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(
												jPanel2Layout
														.createSequentialGroup()
														.addContainerGap()
														.addGroup(
																jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(ituTimerRadioButton)
																		.addComponent(defaultTimerRadioButton).addComponent(customTimerRadioButton))
														.addGap(18, 18, 18)
														.addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
														.addGroup(
																jPanel2Layout
																		.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																		.addGroup(
																				jPanel2Layout
																						.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(jLabel15)
																						.addComponent(customTimerT2TextField, javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addComponent(jLabel14)
																		.addComponent(jLabel17)
																		.addComponent(ituTimerT2TextField, javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(defaultTimerT2TextField, javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addGroup(
												jPanel2Layout
														.createSequentialGroup()
														.addGap(48, 48, 48)
														.addGroup(
																jPanel2Layout
																		.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
																		.addComponent(jLabel11)
																		.addComponent(customTimerT1TextField, javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addGroup(
												jPanel2Layout
														.createSequentialGroup()
														.addGap(48, 48, 48)
														.addGroup(
																jPanel2Layout
																		.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
																		.addComponent(ituTimerT1TextField, javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(jLabel12))))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(
								jPanel2Layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jLabel13)
										.addComponent(jLabel16)
										.addComponent(jLabel18)
										.addComponent(ituTimerT3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(customTimerT3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(defaultTimerT3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)).addContainerGap(20, Short.MAX_VALUE)));

		jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] { customTimerT1TextField, customTimerT2TextField, customTimerT3TextField,
				defaultTimerT2TextField, defaultTimerT3TextField, ituTimerT1TextField, ituTimerT2TextField, ituTimerT3TextField });

		okButton.setFont(new java.awt.Font("Tahoma", 1, 12));
		okButton.setText("OK");
		okButton.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				okButtonActionPerformed(evt);
			}
		});

		jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12));
		jLabel10.setText("Video Location:");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup()
						.addContainerGap()
						.addGroup(
								layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
										.addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addGroup(
												javax.swing.GroupLayout.Alignment.LEADING,
												layout.createSequentialGroup().addGap(181, 181, 181).addComponent(okButton)
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(resetButton).addGap(10, 10, 10)
														.addComponent(startSurveyButton))
										.addGroup(
												javax.swing.GroupLayout.Alignment.LEADING,
												layout.createSequentialGroup().addComponent(jLabel10).addGap(18, 18, 18)
														.addComponent(videoLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(fileChooserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(
												javax.swing.GroupLayout.Alignment.LEADING,
												layout.createSequentialGroup().addComponent(jLabel8).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(surveyNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)).addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup()
						.addGap(18, 18, 18)
						.addGroup(
								layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel8)
										.addComponent(surveyNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(25, 25, 25)
						.addGroup(
								layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel10)
										.addComponent(fileChooserButton)
										.addComponent(videoLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(
								layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(okButton).addComponent(resetButton)
										.addComponent(startSurveyButton)).addContainerGap(39, Short.MAX_VALUE)));
	}// </editor-fold>//GEN-END:initComponents

	protected void ituTimerT3TextFieldActionPerformed(ActionEvent evt) {
		// TODO Auto-generated method stub

	}

	protected void ituTimerT1TextFieldActionPerformed(ActionEvent evt) {
		// TODO Auto-generated method stub

	}

	protected void okButtonActionPerformed(ActionEvent evt) {
		try {
			saveToDatabase();
			JOptionPane.showMessageDialog(null, "Settings are saved successfully.");
			okButton.setEnabled(false);
			resetButton.setEnabled(false);
			startSurveyButton.setEnabled(true);

		} catch (Exception e) {
			JOptionPane.showMessageDialog(null, e.getLocalizedMessage());
		}
	}

	private void qualityRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_qualityRadioButtonActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_qualityRadioButtonActionPerformed

	private void impairmentRadioButtonActionPerformed(ActionEvent evt) {
		// TODO Auto-generated method stub

	}

	private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_resetButtonActionPerformed
		if (evt.getSource() == resetButton) {
			reset();
		}
	}// GEN-LAST:event_resetButtonActionPerformed

	private void startSurveyButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_startSurveyButtonActionPerformed
		mAdminSettingsForm.setVisible(false);
		new MainScreen().setVisible(true);
	}// GEN-LAST:event_startSurveyButtonActionPerformed

	private void fileChooserButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_fileChooserButtonActionPerformed
		final JFileChooser fileChooser = new JFileChooser();
		fileChooser.setDialogTitle("Video directory locator");
		fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
		fileChooser.showOpenDialog(this);
		File selectedFile = fileChooser.getSelectedFile();
		videoLocation.setText(selectedFile.getPath());
	}// GEN-LAST:event_fileChooserButtonActionPerformed

	private void disableCustomAndBinaryScaleTextFields(boolean flag) {
		customScaleMaxTextField.setEditable(flag);
		customScaleMidTextField.setEditable(flag);
		customScaleMinTextField.setEditable(flag);
		binaryScalePositiveTextField.setEditable(flag);
		binaryScaleNegativeTextField.setEditable(flag);
		qualityRadioButton.setEnabled(flag);
		impairmentRadioButton.setEnabled(flag);
	}

	private void surveyNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_surveyNameTextFieldActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_surveyNameTextFieldActionPerformed

	private void customScaleActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_customScaleActionPerformed
		if (customScale.isSelected()) {
			// Make binaryScale text fields uneditable
			disableCustomAndBinaryScaleTextFields(false);
			// Make customScale text fields editable
			customScaleMaxTextField.setEditable(true);
			customScaleMidTextField.setEditable(true);
			customScaleMinTextField.setEditable(true);

		}
	}// GEN-LAST:event_customScaleActionPerformed

	private void cRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cRadioButton2ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_cRadioButton2ActionPerformed

	private void binaryScaleActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_binaryScaleActionPerformed
		if (binaryScale.isSelected()) {
			// Make customScale text fields uneditable
			disableCustomAndBinaryScaleTextFields(false);
			// Make binaryScale text fields editable
			binaryScalePositiveTextField.setEditable(true);
			binaryScaleNegativeTextField.setEditable(true);
		}
	}// GEN-LAST:event_binaryScaleActionPerformed

	private void bRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_bRadioButton2ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_bRadioButton2ActionPerformed

	private void fivePointScaleActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_fivePointScaleActionPerformed
		disableCustomAndBinaryScaleTextFields(false);
		qualityRadioButton.setEnabled(true);
		impairmentRadioButton.setEnabled(true);
	}// GEN-LAST:event_fivePointScaleActionPerformed

	private void hundredPointScaleActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_hundredPointScaleActionPerformed
		disableCustomAndBinaryScaleTextFields(false);

	}// GEN-LAST:event_hundredPointScaleActionPerformed

	private void ituTimerRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ituTimerRadioButtonActionPerformed
		defaultTimerT2TextField.setEditable(false);
		defaultTimerT3TextField.setEditable(false);
		customTimerT1TextField.setEditable(false);
		customTimerT2TextField.setEditable(false);
		customTimerT3TextField.setEditable(false);
	}// GEN-LAST:event_ituTimerRadioButtonActionPerformed

	private void defaultTimerRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_defaultTimerRadioButtonActionPerformed
		defaultTimerT2TextField.setEditable(true);
		defaultTimerT3TextField.setEditable(true);
		customTimerT1TextField.setEditable(false);
		customTimerT2TextField.setEditable(false);
		customTimerT3TextField.setEditable(false);
	}// GEN-LAST:event_defaultTimerRadioButtonActionPerformed

	private void customTimerRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_customTimerRadioButtonActionPerformed
		defaultTimerT2TextField.setEditable(false);
		defaultTimerT3TextField.setEditable(false);
		customTimerT1TextField.setEditable(true);
		customTimerT2TextField.setEditable(true);
		customTimerT3TextField.setEditable(true);
	}// GEN-LAST:event_customTimerRadioButtonActionPerformed

	private void saveToDatabase() throws Exception {

		CustomScale customScale = null;
		BinaryScale binaryScale = null;
		Survey survey = new Survey();
		try {
			survey.setSurveyName(surveyNameTextField.getText());
			survey.setVideoLocation(videoLocation.getText());

			Survey.ScaleType scaleType = getScaleType();

			if (Survey.ScaleType.BINARY_SCALE == scaleType) {
				binaryScale = new BinaryScale();
				binaryScale.setNegativeScale(binaryScaleNegativeTextField.getText());
				binaryScale.setPositiveScale(binaryScalePositiveTextField.getText());
			} else if (Survey.ScaleType.CUSTOM_SCALE == scaleType) {
				customScale = new CustomScale();
				customScale.setMaxScale(customScaleMaxTextField.getText());
				customScale.setMidScale(customScaleMidTextField.getText());
				customScale.setMinScale(customScaleMinTextField.getText());
			}

			survey.setScaleType(scaleType);
			//
			Timer timer = getTimer();
			//
			mAdminSettingsManager.saveSettings(survey, timer, binaryScale, customScale);
		} catch (IllegalArgumentException e) {
			throw new Exception(e.getLocalizedMessage());
		} catch (Exception e) {
			e.printStackTrace();
			throw new Exception(e.getLocalizedMessage());
		}

	}

	private Timer getTimer() {
		final Timer timer = new Timer();
		if (ituTimerRadioButton.isSelected()) {
			timer.setT1(Integer.valueOf(ituTimerT1TextField.getText()));
			timer.setT2(Integer.valueOf(ituTimerT2TextField.getText()));
			timer.setT3(Integer.valueOf(ituTimerT3TextField.getText()));
			timer.setTimerType(Timer.TimerType.ITUTIMER);
		} else if (customTimerRadioButton.isSelected()) {
			timer.setT1(Integer.valueOf(customTimerT1TextField.getText()));
			timer.setT2(Integer.valueOf(customTimerT2TextField.getText()));
			timer.setT3(Integer.valueOf(customTimerT3TextField.getText()));
			timer.setTimerType(Timer.TimerType.CUSTOMTIMER);
		} else if (defaultTimerRadioButton.isSelected()) {
			timer.setT2(Integer.valueOf(defaultTimerT2TextField.getText()));
			timer.setT3(Integer.valueOf(defaultTimerT3TextField.getText()));
			timer.setTimerType(Timer.TimerType.DEFAULTTIMER);
		} else {
			throw new IllegalArgumentException("Please select the timer details");
		}

		return timer;
	}

	private ScaleType getScaleType() {
		if (hundredPointScale.isSelected()) {
			return Survey.ScaleType.CONTINOUS_SCALE;
		} else if (fivePointScale.isSelected()) {
			if (qualityRadioButton.isSelected()) {
				return Survey.ScaleType.FIVE_POINT_QUALITY_SCALE;
			} else if (impairmentRadioButton.isSelected()) {
				return Survey.ScaleType.FIVE_POINT_IMPAIRMENT_SCALE;
			} else {
				throw new IllegalArgumentException("Type of Five point scale is required.");
			}
		} else if (binaryScale.isSelected()) {
			if (binaryScalePositiveTextField.getText() == null || binaryScalePositiveTextField.getText().isEmpty()) {
				throw new IllegalArgumentException("First field of Binary scale is required");
			}
			if (binaryScaleNegativeTextField.getText() == null || binaryScaleNegativeTextField.getText().isEmpty()) {
				throw new IllegalArgumentException("Second field Binary scale is required");
			}
			return Survey.ScaleType.BINARY_SCALE;
		} else if (customScale.isSelected()) {
			if (customScaleMaxTextField.getText() == null || customScaleMaxTextField.getText().isEmpty()) {
				throw new IllegalArgumentException("First field of custom scale is required");
			}
			if (customScaleMidTextField.getText() == null || customScaleMidTextField.getText().isEmpty()) {
				throw new IllegalArgumentException("Second field of custom scale is required");
			}
			if (customScaleMinTextField.getText() == null || customScaleMinTextField.getText().isEmpty()) {
				throw new IllegalArgumentException("Last field of custom scale is required");
			}
			return Survey.ScaleType.CUSTOM_SCALE;
		}
		throw new IllegalArgumentException("Please select the scale type");
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JRadioButton bRadioButton1;
	private javax.swing.JRadioButton bRadioButton2;
	private javax.swing.JRadioButton binaryScale;
	private javax.swing.JTextField binaryScaleNegativeTextField;
	private javax.swing.JTextField binaryScalePositiveTextField;
	private javax.swing.ButtonGroup buttonGroup1;
	private javax.swing.ButtonGroup buttonGroup2;
	private javax.swing.ButtonGroup buttonGroup3;
	private javax.swing.JRadioButton cRadioButton1;
	private javax.swing.JRadioButton cRadioButton2;
	private javax.swing.JRadioButton cRadioButton3;
	private javax.swing.JRadioButton customScale;
	private javax.swing.JTextField customScaleMaxTextField;
	private javax.swing.JTextField customScaleMidTextField;
	private javax.swing.JTextField customScaleMinTextField;
	private javax.swing.JRadioButton customTimerRadioButton;
	private javax.swing.JTextField customTimerT1TextField;
	private javax.swing.JTextField customTimerT2TextField;
	private javax.swing.JTextField customTimerT3TextField;
	private javax.swing.JRadioButton defaultTimerRadioButton;
	private javax.swing.JTextField defaultTimerT2TextField;
	private javax.swing.JTextField defaultTimerT3TextField;
	private javax.swing.JButton fileChooserButton;
	private javax.swing.JRadioButton fivePointScale;
	private javax.swing.JRadioButton hundredPointScale;
	private javax.swing.JRadioButton impairmentRadioButton;
	private javax.swing.JRadioButton ituTimerRadioButton;
	private javax.swing.JTextField ituTimerT1TextField;
	private javax.swing.JTextField ituTimerT2TextField;
	private javax.swing.JTextField ituTimerT3TextField;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel15;
	private javax.swing.JLabel jLabel16;
	private javax.swing.JLabel jLabel17;
	private javax.swing.JLabel jLabel18;
	private javax.swing.JLabel jLabel19;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JSlider jSlider1;
	private javax.swing.JButton okButton;
	private javax.swing.JRadioButton qualityRadioButton;
	private javax.swing.JButton resetButton;
	private javax.swing.JButton startSurveyButton;
	private javax.swing.JTextField surveyNameTextField;
	private javax.swing.JTextField videoLocation;

	// End of variables declaration//GEN-END:variables

	private void reset() {
		surveyNameTextField.setText("");
		videoLocation.setText("");
		buttonGroup1.clearSelection();
		buttonGroup2.clearSelection();
		disableCustomAndBinaryScaleTextFields(false);
	}

}
